// File: ADD.v
// Generated by MyHDL 1.0dev
// Date: Wed Nov  2 10:17:56 2016


`timescale 1ns/10ps

module ADD (
    datain1,
    datain2,
    dataout
);


input [31:0] datain1;
input [31:0] datain2;
output [31:0] dataout;
wire [31:0] dataout;





assign dataout = (datain1 + datain2);

endmodule
