// File: ADD_4.v
// Generated by MyHDL 1.0dev
// Date: Wed Nov  2 10:17:56 2016


`timescale 1ns/10ps

module ADD_4 (
    datain,
    dataout
);


input [31:0] datain;
output [31:0] dataout;
wire [31:0] dataout;





assign dataout = (datain + 4);

endmodule
