// File: AND.v
// Generated by MyHDL 1.0dev
// Date: Sat Nov 26 17:29:15 2016


`timescale 1ns/10ps

module AND (
    data1,
    data2,
    dataout
);


input [31:0] data1;
input [31:0] data2;
output [31:0] dataout;
wire [31:0] dataout;





assign dataout = (data1 & data2);

endmodule
