// File: Demux.v
// Generated by MyHDL 1.0dev
// Date: Tue Nov 29 12:59:58 2016


`timescale 1ns/10ps

module Demux (
    Sel_Demux,
    in_demux,
    out1_demux,
    out2_demux
);


input [0:0] Sel_Demux;
input [31:0] in_demux;
output [31:0] out1_demux;
reg [31:0] out1_demux;
output [31:0] out2_demux;
reg [31:0] out2_demux;




always @(in_demux, Sel_Demux) begin: DEMUX_BEHAVIOR_DEMUX
    out1_demux = 0;
    out2_demux = 0;
    if ((Sel_Demux == 0)) begin
        out1_demux = in_demux;
    end
    else begin
        out2_demux = in_demux;
    end
end

endmodule
