// File: Mux1.v
// Generated by MyHDL 1.0dev
// Date: Tue Nov 29 12:59:58 2016


`timescale 1ns/10ps

module Mux1 (
    RegDest,
    in1_Mux1,
    in2_Mux1,
    in3_Mux1,
    in4_Mux1,
    in5_Mux1,
    output_Mux1
);


input [3:0] RegDest;
input [31:0] in1_Mux1;
input [31:0] in2_Mux1;
input [31:0] in3_Mux1;
input [31:0] in4_Mux1;
input [31:0] in5_Mux1;
output [31:0] output_Mux1;
reg [31:0] output_Mux1;




always @(in2_Mux1, in4_Mux1, in1_Mux1, in3_Mux1, RegDest, in5_Mux1) begin: MUX1_BEHAVIOR_MUX1
    case (RegDest)
        'h0: begin
            output_Mux1 = in1_Mux1;
        end
        'h1: begin
            output_Mux1 = in2_Mux1;
        end
        'h2: begin
            output_Mux1 = in3_Mux1;
        end
        'h3: begin
            output_Mux1 = in4_Mux1;
        end
        'h4: begin
            output_Mux1 = in5_Mux1;
        end
        default: begin
            output_Mux1 = 0;
        end
    endcase
end

endmodule
