// File: Mux3.v
// Generated by MyHDL 1.0dev
// Date: Tue Nov 29 12:59:58 2016


`timescale 1ns/10ps

module Mux3 (
    Sel_Mux,
    in1_Mux3,
    in2_Mux3,
    output_Mux3
);


input [0:0] Sel_Mux;
input [31:0] in1_Mux3;
input [31:0] in2_Mux3;
output [31:0] output_Mux3;
reg [31:0] output_Mux3;




always @(Sel_Mux, in2_Mux3, in1_Mux3) begin: MUX3_BEHAVIOR_MUX3
    if ((Sel_Mux == 0)) begin
        output_Mux3 = in1_Mux3;
    end
    else begin
        output_Mux3 = in2_Mux3;
    end
end

endmodule
