// File: Mux4.v
// Generated by MyHDL 1.0dev
// Date: Tue Nov 29 12:59:58 2016


`timescale 1ns/10ps

module Mux4 (
    PCsrc,
    in1_Mux4,
    in2_Mux4,
    output_Mux4
);


input [0:0] PCsrc;
input [31:0] in1_Mux4;
input [31:0] in2_Mux4;
output [31:0] output_Mux4;
reg [31:0] output_Mux4;




always @(in2_Mux4, in1_Mux4, PCsrc) begin: MUX4_BEHAVIOR_MUX4
    if ((PCsrc == 0)) begin
        output_Mux4 = {in1_Mux4[32-1:1], (0 != 0)};
    end
    else begin
        output_Mux4 = in2_Mux4;
    end
end

endmodule
